spring:
  web:
    resources:
      static-locations:
        - classpath:/static/

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://star-mysql:3306/star-enterprise-society?serverTimezone=UTC&characterEncoding=utf-8
#    url: jdbc:mysql://8.133.207.182:3307/star-enterprise-society?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: zx25805214

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB
      file-size-threshold: 500KB

  main:
    allow-circular-references: true

  data:
    redis:
      database: 0
      host: star-redis
      port: 6379
      timeout: 3000
      lettuce:
        pool:
          min-idle: 0
          max-idle: 8
          max-active: 8
          max-wait: -1ms

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

server:
  port: 9002
  servlet:
    context-path: /star

file:
  banner-dir: /user/banner/
  head-dir: /user/head/
  result-dir: /user/result/
  card-dir: /user/card/
  activity-dir: /user/activity/
  resource-dir: /user/resource/
  product-dir: /user/product/
  demand-dir: /user/demand/
  enterprise-dir: /user/enterprise/

my:
  appid: wxc0e98dcbf0b62a53
  secret: 09aad0d97c7f1038f7ceddaa6c651a28
